// @author Fourseagulls
package ventanas;

import complementos.SonidoBotonComentado;
import extra.CalculosConMath;
import extra.CaracteresEspeciales;
import java.io.IOException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tareas.Operaciones;
/**
 *
 * @author Usuario
 */
public class VPrincipal extends javax.swing.JFrame {
    
    boolean invisible=false;
    
    public VPrincipal() {
        initComponents();
        iniciarComponentes();
    }

    private void iniciarComponentes(){
        System.out.println("Estoy funcionando");
        intro_btn_1.setVisible(false);
        intro_lbl_3.setVisible(false);
        intro_lbl_2.setVisible(false);
        intro_btn_3.setVisible(false);
        intro_btn_2.setVisible(false);
        primer_reto_lbl.setVisible(false);
        primer_reto_btn.setVisible(false);
        forastero2_lbl.setVisible(false);
        forastero3_lbl.setVisible(false);
        cerradura_btn.setVisible(false);
        
        pnl_botones.setVisible(false);
        
        tableroPrin.setEnabledAt(1, false);
        tableroPrin.setEnabledAt(2, false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnl_cabecera = new javax.swing.JPanel();
        lbl_cabecera = new javax.swing.JLabel();
        iconoDch = new javax.swing.JLabel();
        iconoIzq = new javax.swing.JLabel();
        tableroPrin = new javax.swing.JTabbedPane();
        pnl_Tab_Intro = new javax.swing.JPanel();
        intro_btn_1 = new javax.swing.JButton();
        intro_lbl_1 = new javax.swing.JLabel();
        intro_btn_2 = new javax.swing.JButton();
        intro_lbl_2 = new javax.swing.JLabel();
        intro_btn_3 = new javax.swing.JButton();
        intro_lbl_3 = new javax.swing.JLabel();
        pnl_primer_reto = new javax.swing.JPanel();
        forastero_lbl = new javax.swing.JLabel();
        forastero0_lbl = new javax.swing.JLabel();
        primer_reto_btn = new javax.swing.JButton();
        primer_reto_lbl = new javax.swing.JLabel();
        forastero2_lbl = new javax.swing.JLabel();
        forastero3_lbl = new javax.swing.JLabel();
        cerradura_btn = new javax.swing.JButton();
        pnl_segundo_reto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnl_botones = new javax.swing.JPanel();
        btn_lanzaPuzzle = new javax.swing.JButton();
        btn_preguntas = new javax.swing.JButton();
        btn_geometria = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btn_comodin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setBounds(500,100,720,540);
        setLocation(new java.awt.Point(500, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 540));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_cabecera.setBackground(new java.awt.Color(102, 153, 255));
        pnl_cabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cabecera.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cabecera.setText("<html><div align=center>LOCOS POR EL CÓDIGO<br> Esto es una prática de programación con JAVA<br><b> Para entrar tienes que seguir las instrucciones veladas</b><br><b>o hacer lo contrario</b> y se abrirá el panel de mandos. </div>");
        pnl_cabecera.add(lbl_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 460, 100));

        iconoDch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoDch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoDespaChocho1.png"))); // NOI18N
        pnl_cabecera.add(iconoDch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 131, 100));

        iconoIzq.setBackground(new java.awt.Color(102, 153, 255));
        iconoIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoDespacho.png"))); // NOI18N
        iconoIzq.setMaximumSize(new java.awt.Dimension(140, 100));
        iconoIzq.setOpaque(true);
        iconoIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoIzqMouseClicked(evt);
            }
        });
        pnl_cabecera.add(iconoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 143, -1));

        jPanel2.add(pnl_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tableroPrin.setBackground(new java.awt.Color(102, 153, 255));

        pnl_Tab_Intro.setBackground(new java.awt.Color(102, 153, 255));
        pnl_Tab_Intro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        intro_btn_1.setBackground(new java.awt.Color(102, 153, 255));
        intro_btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye_48.png"))); // NOI18N
        intro_btn_1.setText("Me apunto");
        intro_btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intro_btn_1ActionPerformed(evt);
            }
        });
        pnl_Tab_Intro.add(intro_btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 128, -1, 50));

        intro_lbl_1.setBackground(new java.awt.Color(102, 153, 255));
        intro_lbl_1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        intro_lbl_1.setForeground(new java.awt.Color(0, 0, 0));
        intro_lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intro_lbl_1.setText("<html>\n¿Quieres resolver el primer misterios?<br>\nHay un lugar secrto que te hará entrar<br><br>\nTienes que encontrar el lugar <br>\nque actuva la puerta<br>");
        intro_lbl_1.setOpaque(true);
        pnl_Tab_Intro.add(intro_lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 327, 129));

        intro_btn_2.setBackground(new java.awt.Color(102, 153, 255));
        intro_btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye_48.png"))); // NOI18N
        intro_btn_2.setText("Sí quiero");
        intro_btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intro_btn_2ActionPerformed(evt);
            }
        });
        pnl_Tab_Intro.add(intro_btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, 40));

        intro_lbl_2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        intro_lbl_2.setForeground(new java.awt.Color(0, 0, 0));
        intro_lbl_2.setText("<html>\nTendrás que superar todos los desafíos<br>\npara ir desbloqueando los poderes superiores<br>");
        pnl_Tab_Intro.add(intro_lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 159, 327, 95));

        intro_btn_3.setBackground(new java.awt.Color(102, 153, 255));
        intro_btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye_48.png"))); // NOI18N
        intro_btn_3.setText("Activar Primer reto");
        intro_btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intro_btn_3ActionPerformed(evt);
            }
        });
        pnl_Tab_Intro.add(intro_btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, 40));

        intro_lbl_3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        intro_lbl_3.setForeground(new java.awt.Color(0, 0, 0));
        intro_lbl_3.setText("<html>\nSi quieres salvar el mundo tendrás que aprender<br>\na pasar por tonto<br>");
        pnl_Tab_Intro.add(intro_lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 327, 70));

        tableroPrin.addTab("Información", pnl_Tab_Intro);

        pnl_primer_reto.setBackground(new java.awt.Color(102, 153, 255));
        pnl_primer_reto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forastero_lbl.setBackground(new java.awt.Color(255, 153, 51));
        forastero_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        forastero_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forastero_lbl.setText("<html>Si estás viendo esto es que entraste<br> sin seguir los pasos de iniciación<br> ");
        forastero_lbl.setOpaque(true);
        forastero_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forastero_lblMouseEntered(evt);
            }
        });
        pnl_primer_reto.add(forastero_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 331, 40));

        forastero0_lbl.setBackground(new java.awt.Color(255, 153, 51));
        forastero0_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forastero0_lbl.setText("<html> <h2>De un paso atrás foratero!!!</h2>");
        forastero0_lbl.setOpaque(true);
        pnl_primer_reto.add(forastero0_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 330, 50));

        primer_reto_btn.setBackground(new java.awt.Color(102, 153, 255));
        primer_reto_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow_48.png"))); // NOI18N
        primer_reto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primer_reto_btnActionPerformed(evt);
            }
        });
        pnl_primer_reto.add(primer_reto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 60, -1));

        primer_reto_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        primer_reto_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer_reto_lbl.setText("<html>\nAlpulsar el botón se lanzará un número aleatorio<br>\nSe te dan site intentos para allarlo<br>\nNo te preocupes sé que puedes y <br>\nrecibirás ayuda.");
        pnl_primer_reto.add(primer_reto_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 355, 84));

        forastero2_lbl.setBackground(new java.awt.Color(255, 153, 0));
        forastero2_lbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        forastero2_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forastero2_lbl.setText("<html>\nNo insistas tienes que volver<br>\n y descubrir elcamino.");
        forastero2_lbl.setOpaque(true);
        forastero2_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forastero2_lblMouseEntered(evt);
            }
        });
        pnl_primer_reto.add(forastero2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 60));

        forastero3_lbl.setBackground(new java.awt.Color(255, 102, 0));
        forastero3_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forastero3_lbl.setText("<html>Poraquí no vas a encontrar lapuerta.\n<h2>No pierdas tiempo</h2>");
        forastero3_lbl.setOpaque(true);
        forastero3_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forastero3_lblMouseEntered(evt);
            }
        });
        pnl_primer_reto.add(forastero3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 330, 60));

        cerradura_btn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cerradura_btn.setText("Activa lapuerta y encuentrala.");
        cerradura_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerradura_btnActionPerformed(evt);
            }
        });
        pnl_primer_reto.add(cerradura_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 330, -1));

        tableroPrin.addTab("Tu primer reto", pnl_primer_reto);

        pnl_segundo_reto.setBackground(new java.awt.Color(102, 153, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Esta ya te sorprenderá.");

        javax.swing.GroupLayout pnl_segundo_retoLayout = new javax.swing.GroupLayout(pnl_segundo_reto);
        pnl_segundo_reto.setLayout(pnl_segundo_retoLayout);
        pnl_segundo_retoLayout.setHorizontalGroup(
            pnl_segundo_retoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_segundo_retoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_segundo_retoLayout.setVerticalGroup(
            pnl_segundo_retoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_segundo_retoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableroPrin.addTab("Segundo reto", pnl_segundo_reto);

        jPanel2.add(tableroPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 410));

        pnl_botones.setBackground(new java.awt.Color(102, 153, 255));
        pnl_botones.setMaximumSize(new java.awt.Dimension(150, 50));
        pnl_botones.setPreferredSize(new java.awt.Dimension(320, 400));
        pnl_botones.setLayout(new java.awt.GridLayout(8, 2));

        btn_lanzaPuzzle.setText("Puzzle");
        btn_lanzaPuzzle.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_lanzaPuzzle.setMinimumSize(new java.awt.Dimension(25, 25));
        btn_lanzaPuzzle.setPreferredSize(new java.awt.Dimension(70, 60));
        btn_lanzaPuzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lanzaPuzzleActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_lanzaPuzzle);

        btn_preguntas.setText("Preguntas");
        btn_preguntas.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_preguntas.setPreferredSize(new java.awt.Dimension(70, 60));
        btn_preguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preguntasActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_preguntas);

        btn_geometria.setText("Geometría");
        btn_geometria.setMaximumSize(new java.awt.Dimension(150, 50));
        btn_geometria.setPreferredSize(new java.awt.Dimension(70, 60));
        btn_geometria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geometriaActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_geometria);

        jButton7.setText("Botón con sonido");
        jButton7.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton7);

        jButton5.setText("Botones Musicales");
        jButton5.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton5);

        jButton3.setText("Botón Sonido Comentado");
        jButton3.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton3);

        jButton4.setText("Preguntas Musicales");
        jButton4.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton4);

        jButton2.setText("jButton2");
        jButton2.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 60));
        pnl_botones.add(jButton2);

        jButton8.setText("jButton8");
        jButton8.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(70, 60));
        pnl_botones.add(jButton8);

        jButton9.setText("jButton9");
        jButton9.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton9.setPreferredSize(new java.awt.Dimension(70, 60));
        pnl_botones.add(jButton9);

        jButton10.setText("jButton10");
        jButton10.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton10.setPreferredSize(new java.awt.Dimension(70, 60));
        pnl_botones.add(jButton10);

        jButton11.setText("jButton11");
        jButton11.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton11.setPreferredSize(new java.awt.Dimension(70, 60));
        pnl_botones.add(jButton11);

        jButton12.setText("Caracteres Especiales");
        jButton12.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton12.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton12);

        jButton13.setText("JButton VVacío");
        jButton13.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton13.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton13);

        jButton17.setText("Raiz y Random");
        jButton17.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton17.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        pnl_botones.add(jButton17);

        btn_comodin.setText("Botón Comodin");
        btn_comodin.setPreferredSize(new java.awt.Dimension(70, 60));
        btn_comodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comodinActionPerformed(evt);
            }
        });
        pnl_botones.add(btn_comodin);

        jPanel2.add(pnl_botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 320, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerradura_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerradura_btnActionPerformed
        forastero_lbl.setVisible(false);
        forastero2_lbl.setVisible(false);
        invisible=true;
        intro_btn_1.setVisible(true);

        //soni_muybien();
    }//GEN-LAST:event_cerradura_btnActionPerformed

    private void forastero3_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forastero3_lblMouseEntered
        cerradura_btn.setVisible(true);
    }//GEN-LAST:event_forastero3_lblMouseEntered

    private void forastero2_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forastero2_lblMouseEntered
        forastero3_lbl.setVisible(true);
    }//GEN-LAST:event_forastero2_lblMouseEntered

    private void primer_reto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primer_reto_btnActionPerformed
        pnl_botones.setVisible(true);
    }//GEN-LAST:event_primer_reto_btnActionPerformed

    private void forastero_lblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forastero_lblMouseEntered
        if(invisible==false){
            forastero2_lbl.setVisible(true);
        }

    }//GEN-LAST:event_forastero_lblMouseEntered

    private void intro_btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intro_btn_3ActionPerformed
        //perfecto();

        forastero0_lbl.setVisible(false);
        forastero3_lbl.setVisible(false);
        forastero2_lbl.setVisible(false);
        cerradura_btn.setVisible(false);
        forastero_lbl.setOpaque(false);
        forastero_lbl.setText("<html>Veo que te has preparado<br>"
            + "para dar el gran paso<br>");
        forastero0_lbl.setOpaque(false);
        forastero0_lbl.setText("<html><h2>¡¡Adelantecampeón!!");
        forastero_lbl.setVisible(true);
        forastero0_lbl.setVisible(true);
        primer_reto_lbl.setVisible(true);
        primer_reto_btn.setVisible(true);
    }//GEN-LAST:event_intro_btn_3ActionPerformed

    private void intro_btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intro_btn_2ActionPerformed
        intro_lbl_3.setVisible(true);
        intro_btn_3.setVisible(true);
    }//GEN-LAST:event_intro_btn_2ActionPerformed

    private void intro_btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intro_btn_1ActionPerformed
        intro_lbl_2.setVisible(true);
        intro_btn_2.setVisible(true);
    }//GEN-LAST:event_intro_btn_1ActionPerformed

    private void btn_geometriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geometriaActionPerformed
        //INSTRUCCIONES
        JOptionPane.showMessageDialog(null, "<html><div align=center><h2>Se van a presentar<br>una serie de preguntas<br> que has de contestar correctamente.<br>Presta atención al escribir las respuestas</h2></div>");
        //CREAMOS LA VENTANA
        JFrame ventana = new JFrame("Preguntas Geometría");
        ventana.getContentPane();

        ventana.setSize(400, 600);
        ventana.setLocationRelativeTo(ventana);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
        
        //INTRODUCIMOS NUESTRA CLASE EN LA VENTANA
        PreguntasGeometria vPreguntas = new PreguntasGeometria();
        ventana.add(vPreguntas.getTablero());
    }//GEN-LAST:event_btn_geometriaActionPerformed

    private void btn_lanzaPuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lanzaPuzzleActionPerformed

        VentanaPuzzle vp = new VentanaPuzzle();
        vp.desordena();
        vp.setVisible(true);

    }//GEN-LAST:event_btn_lanzaPuzzleActionPerformed

    private void btn_comodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comodinActionPerformed
        Operaciones.operar();
        lbl_cabecera.setText("<html>Veo que tienes <br>ganas de empezar");
    }//GEN-LAST:event_btn_comodinActionPerformed

    private void btn_preguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preguntasActionPerformed
        JFrame ventana = new JFrame("Uso pestañotas");
        ventana.getContentPane();
        VPreguntas pestanotas = new VPreguntas();
        ventana.add(pestanotas.getTablero());

        ventana.setSize(400, 300);
        ventana.setLocationRelativeTo(ventana);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_preguntasActionPerformed

    private void iconoIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoIzqMouseClicked
        tableroPrin.setEnabledAt(1, true);
    }//GEN-LAST:event_iconoIzqMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        CalculosConMath calculos = new CalculosConMath();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        CaracteresEspeciales caracteres = new CaracteresEspeciales();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        VClick vClick = new VClick();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VMusical vMusical = new VMusical();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SonidoBotonComentado soniBoton = new SonidoBotonComentado();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VPreguntasMusicales pMusicales = new VPreguntasMusicales();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VPrincipal().setVisible(true);
        });
    }
    
    private void perfecto(){
        try {
                    // Obtener el archivo de sonido
                    Clip clip = AudioSystem.getClip();
                    clip.open(AudioSystem.getAudioInputStream(
                            SonidoClick.class.getResourceAsStream("/sonido/perfectoActiva.wav")));
                    clip.start();
                } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                }
    }
    
     private void soni_muybien(){
        try {
                    // Obtener el archivo de sonido
                    Clip clip = AudioSystem.getClip();
                    clip.open(AudioSystem.getAudioInputStream(
                            SonidoClick.class.getResourceAsStream("/sonido/muybien.wav")));
                    clip.start();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comodin;
    private javax.swing.JButton btn_geometria;
    private javax.swing.JButton btn_lanzaPuzzle;
    private javax.swing.JButton btn_preguntas;
    private javax.swing.JButton cerradura_btn;
    private javax.swing.JLabel forastero0_lbl;
    private javax.swing.JLabel forastero2_lbl;
    private javax.swing.JLabel forastero3_lbl;
    private javax.swing.JLabel forastero_lbl;
    private javax.swing.JLabel iconoDch;
    private javax.swing.JLabel iconoIzq;
    private javax.swing.JButton intro_btn_1;
    private javax.swing.JButton intro_btn_2;
    private javax.swing.JButton intro_btn_3;
    private javax.swing.JLabel intro_lbl_1;
    private javax.swing.JLabel intro_lbl_2;
    private javax.swing.JLabel intro_lbl_3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_cabecera;
    private javax.swing.JPanel pnl_Tab_Intro;
    private javax.swing.JPanel pnl_botones;
    private javax.swing.JPanel pnl_cabecera;
    private javax.swing.JPanel pnl_primer_reto;
    private javax.swing.JPanel pnl_segundo_reto;
    private javax.swing.JButton primer_reto_btn;
    private javax.swing.JLabel primer_reto_lbl;
    private javax.swing.JTabbedPane tableroPrin;
    // End of variables declaration//GEN-END:variables
}
